### ISSUE TITLE
how can change api?

### ISSUE THREAD

**Issue by lolminerxmrig** [codemachine8/Unfold-AI#1]
Hi.
can change api code?

**Comment by codemachine8** [comment]
Hello,

Thank you for reaching out! To update your API key in VS Code, please follow these steps:

Open the Command Palette by typing Ctrl+Shift+P (or Cmd+Shift+P on Mac).
In the Command Palette, type > and then enter UnfoldAI: Clear API Key.
Follow the prompt to clear your existing API key.
After completing this step, close the application.
Relaunch the application and log in again.
You can then submit your new API key.
I hope this clarifies the process. If you have any more questions or need further assistance, feel free to ask!

**Comment by codemachine8** [comment]
answered
